# Generated by Django 5.0.3 on 2024-04-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('entradas', models.CharField(max_length=200)),
                ('postre', models.CharField(max_length=200)),
                ('platoPrincipal', models.CharField(max_length=200)),
            ],
        ),
    ]
